[package]
name = "cpptoken"
version = "0.1.0"
authors = ["Qiang Kou <qkou@qkou.info>"]
license = "Apache-2.0"

[lib]
name = "cpptoken"
crate-type = ["staticlib", "cdylib"]

[dependencies]
tokenizers = { path = "../../tokenizers" }
