name: Python

on:
  push:
    branches:
      - master
    paths-ignore:
      - bindings/node/**
  pull_request:
    paths-ignore:
      - bindings/node/**

jobs:
  code_quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: "x64"

      - name: Install dependencies
        run: pip install black

      - name: Check style
        working-directory: ./bindings/python
        run: make check-style

  build_and_test:
    name: Check everything builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      # Necessary for now for the cargo cache: https://github.com/actions/cache/issues/133#issuecomment-599102035
      - run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - name: Cache Cargo Registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

      - name: Cache Cargo Build Target
        uses: actions/cache@v1
        with:
          path: ./bindings/python/target
          key: ${{ runner.os }}-cargo-python-build-${{ hashFiles('**/Cargo.toml') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --verbose --manifest-path ./bindings/python/Cargo.toml

      - name: Lint with RustFmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --manifest-path ./bindings/python/Cargo.toml -- --check
